### ISSUE TITLE
使用时候遇到的bug

### ISSUE THREAD

**Issue by Moober** [MoePlayer/hexo-tag-dplayer#14]
1，在电脑端使用的时候 ，首页面会出现 乱码的情况

![image](https://user-images.githubusercontent.com/26390644/33010871-01f06b1a-ce17-11e7-9764-9454a59c326e.png)

2，在手机端首页和电脑端一样乱码，更大的问题是，在手机端Safari、Google、QQ浏览器 均不可以播放，Safari、Google，点击播放后无反应，QQ浏览器则提示：地址无效正在跳转……，

3，我用的是七牛云链接的MP4的视频：http://ozpj5yy3b.bkt.clouddn.com/01.mp4

**Comment by dixyes** [comment]
使用的theme可能过滤了script标签（？）
希望提供theme名称或者仓库地址

moober.cn文章内的视频在chrome mobile 62.0.3202.84（在Nexus 5X，Android 8.0.0）可以正常播放，如果是ios的safari出现问题，可以在Dplayer仓库提交问题

**Comment by Moober** [comment]
@dixyes  用的是  next  ，   我是在 苹果手机上使用的 chrome mobile 60.0.3112.89

**Comment by Moober** [comment]
今天发现，原文档中的视频 是可以在手机上看的，而我的就不行，不知道原因，你的那个视频也是七牛云的吗？

**Comment by dixyes** [comment]
用next默认设置和Pisces shceme并没重现问题（思考

视频能否正常播放主要还是看浏览器的支持(dplayer.js仅仅包装了html video并且加入了弹幕功能) 浏览器不支持的视频考虑使用mse的插件如flv.js和hls.js等

可以考虑把视频转码到一种各种浏览器都支持的视频 [mdn参考](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility)（目测h264+aac用mp4封装比较好）

**Comment by Moober** [comment]
@dixyes 
1.我用的主题就是 Piscess
2.目前尴尬的问题是 在 电脑上没问题，手机就有问题，也是用苹果的浏览器，用的谷歌浏览器，
3..我的视频的封装就是你说的这种，我用你的用例中的视频没问题可以播放 电脑和手机都可以的，而我的视频在手机上就可以播放，不知道为什么，

**Comment by Moober** [comment]
如果方便你可以试试我放出来的视频链接

**Comment by DIYgod** [comment]
iOS Safari chrome 微信 均无法复现，我这里可以正常播放

**Comment by Moober** [comment]
@DIYgod moober.cn 你进去播放看看 用手机打开，在我这里第一个视频无法播放，第二个视频是你们原来的案例里面的视频 可以播放，我很郁闷，感谢你的回答

**Comment by dixyes** [comment]
我去找小伙伴借了个苹果看了看 应该不是dplayer的问题

目测是你开了弹幕功能 而弹幕api的跨域头没有允许所以报错

而视频加载不出来可能是糟糕的缓存策略导致的，需要等他缓存

至于script标签被吃了的问题 没法复现啊

**Comment by Moober** [comment]
1.首页出现代码的问题 我知道是为什么了，是因为 主题设置的字数限制导致的，
2.我也觉得应该不是dplayer 的问题了
3.我想知道你们的视频是放在七牛云上了吗？，你们的转码格式使用转的

**Comment by grzhan** [comment]
一些主题限制字数的 excerpt 有时候会出现这类问题
这种情况我觉得一般去调整主题本身会比较好

**Comment by Moober** [comment]
嗯嗯，我是小白，所以主题调整 还一脸懵逼，没找到那里可以调整主页的布局

**Comment by Myer921** [comment]
时间超时，暂时冻结
