### ISSUE TITLE
css and js can not be loaded when blog is in a subdir

### ISSUE THREAD

**Issue by CharlesLiu7** [MoePlayer/hexo-tag-dplayer#19]
TL;DR : you use the same logic to generate the `DPlayer.min.js` and find the `DPlayer.min.js` in stylesheet.

Details:
I put my blog in a subdirectory, i.e. in `_config.yml
```
url: https://xxx.me
root: /blog/
```
And I set `styleDir = '/blog/assets/css/'`, now it puts the  `DPlayer.min.js` in `'https:xxx.me/blog/blog/assests/css/` and the stylesheet tries to find it `https:xxx.me/blog/assests/css/`. WRONG!

THX

**Comment by dixyes** [comment]
try this
https://github.com/dixyes/hexo-tag-dplayer
in commit 8031282974e78d6e9db324557c3c4be49cdbf0c7

**Comment by CharlesLiu7** [comment]
THX
