### ISSUE TITLE
另外一个关于加载的坑

### ISSUE THREAD

**Issue by Myer921** [MoePlayer/hexo-tag-dplayer#2]
如何才能在用户”看到“的时候执行加载呢？
一个页面同时有3,4个视频跑加载，很卡的样子

https://morz.org/archives/2016/09/06/[%E8%A7%86%E9%A2%91%E5%88%86%E4%BA%AB]%20%E9%BA%BB%E6%9E%9D%E5%87%86%E5%8F%99%E4%BA%8B%E6%AD%8C%E7%B3%BB%E5%88%97/index.html

@dixyes 不知道你有什么可以探讨的方案

**Comment by dixyes** [comment]
这不是插件的锅也并非插件要解决的问题，请移步dplayer提交issue
