### ISSUE TITLE
"Cannot read property '_id' of undefined"

### ISSUE THREAD

**Issue by dixyes** [MoePlayer/hexo-tag-dplayer#21]
@leizh81顺便提供下环境 吃完饭回去看看

**Comment by dixyes** [comment]
见于反馈 https://github.com/MoePlayer/DPlayer/issues/31#issuecomment-384493027
我的锅 不清楚js里匿名函数和箭头函数的区别导致的
修复于 fd96a57a56356aeab64d3dba685f48cc292736b5

**Comment by leizh81** [comment]
hexo: 3.5.0
hexo-cli: 1.0.4
os: Linux 4.9.35-v7+ linux arm
http_parser: 2.7.0
node: 9.5.0

买了个raspberrypi玩传感器，顺带建的个人博客。。。。
感谢

**Comment by dixyes** [comment]
@leizh81试试github.com/dixyes/hexo-tag-dplayer这个的master

（或者说提交 fd96a57a56356aeab64d3dba685f48cc292736b5

如果没问题了我推到这里 未来再推到npm

**Comment by leizh81** [comment]
感谢大神，修改了那一行代码已经解决问题了，
