### ISSUE TITLE
unknown block tag: dplayer

### ISSUE THREAD

**Issue by napoleonthirteen** [MoePlayer/hexo-tag-dplayer#9]
unknown block tag: dplayer.    how to fix it?

**Comment by dixyes** [comment]
ensure you have hexo-tag-dplayer npm module installed in your hexo dir
if you already have, use raw tag to use dplayer, I will try to fix it, any pull request for this issue is welcome

**Comment by JYG0723** [comment]
Will such a problem happen? How to fix it?

**Comment by dixyes** [comment]
@JYG0723 if you have not installed the correct plugin

or i dont known why

你没装插件时会提示找不到tag

或者我就不知道咋回事了

（这个问题没有任何继续反馈 不知道是否仍然发生 就暂且晾着 有相似问题可以在这里交流）

**Comment by JYG0723** [comment]
非常感谢你的回答。这个问题我已经解决。是自己疏忽的问题
```
npm install hexo-tag-dplayer
```

**Comment by dixyes** [comment]
@JYG0723
而且你应该在博客目录使用 --save安装

顺便安利测试[新版](https://github.com/dixyes/hexo-tag-dplayer)（还没有merge到仓库）

**Comment by JYG0723** [comment]
多谢指正。哈哈，我试一下
